//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostsCommentsMonolitono.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabPost
    {
        public int id { get; set; }
        public string NomeConta { get; set; }
        public string Comentarios { get; set; }
        public string Foto { get; set; }
    }
}
